twitter:
    app_key:
    app_secret:
    consumer_token:
    consumer_secret:

db:
    connection: # See: https://dataset.readthedocs.org/en/latest/quickstart.html#connecting-to-a-database
    datatype:

# The inital coordinates (latlong) for the bounding box
coordinates:
    ne: []
    sw: []
